### ISSUE TITLE
Error Uncaught RuntimeException

### ISSUE THREAD

**Issue by ammarfaizi2** [ircmaxell/php-compiler#59]
Hello, I got an error when running JIT and AOT. It is only working properly for the VM.
Did I miss something here?

## Used Repo
```
commit 3ed4119240bbcbde885dcd74a39d6958aa9389ef (HEAD -> master, origin/master, origin/HEAD)
Author: Anthony Ferrara <ircmaxell@gmail.com>
Date:   Mon Apr 22 10:18:07 2019 -0400

    Improve performance drastically by updating phpllvm
```

## test.php
```php
<?php
echo "Hello World\n";
```

## Error JIT
```
ammarfaizi2@berlin:~/project/now/php-compiler$ ../php7.4/sapi/cli/php bin/jit.php test.php

Fatal error: Uncaught RuntimeException: Module verification failed due to Intrinsic has incorrect argument type!
void (i8*, i8, i64, i32, i1)* @llvm.memset.p0i8.i64
Intrinsic has incorrect argument type!
void (i8*, i8, i64, i32, i1)* @llvm.memset.p0i8.i64
Intrinsic has incorrect argument type!
void (i8*, i8*, i64, i32, i1)* @llvm.memcpy.p0i8.p0i8.i64
Intrinsic has incorrect argument type!
void (i8*, i8*, i64, i32, i1)* @llvm.memcpy.p0i8.p0i8.i64
Intrinsic has incorrect argument type!
void (i8*, i8*, i64, i32, i1)* @llvm.memcpy.p0i8.p0i8.i64
Intrinsic has incorrect argument type!
void (i8*, i8*, i64, i32, i1)* @llvm.memcpy.p0i8.p0i8.i64
 in /home/ammarfaizi2/project/now/php-compiler/vendor/ircmaxell/php-llvm/lib/LLVMAbstract/Module.php:180
Stack trace:
#0 /home/ammarfaizi2/project/now/php-compiler/lib/JIT/Context.php(210): PHPLLVM\LLVMAbstract\Module->verify(4, 'Intrinsic has i...')
#1 /home/ammarfaizi2/project/now/php-compiler/lib/JIT/Context.php(182): PHPCompiler\JIT\Context->compileCommon()
#2 /home/ammarfaizi2/project/ in /home/ammarfaizi2/project/now/php-compiler/vendor/ircmaxell/php-llvm/lib/LLVMAbstract/Module.php on line 180
ammarfaizi2@berlin:~/project/now/php-compiler$ 
```

## Error compile
```
ammarfaizi2@berlin:~/project/now/php-compiler$ ../php7.4/sapi/cli/php bin/compile.php test.php

Fatal error: Uncaught RuntimeException: Module verification failed due to Intrinsic has incorrect argument type!
void (i8*, i8, i64, i32, i1)* @llvm.memset.p0i8.i64
Intrinsic has incorrect argument type!
void (i8*, i8, i64, i32, i1)* @llvm.memset.p0i8.i64
Intrinsic has incorrect argument type!
void (i8*, i8*, i64, i32, i1)* @llvm.memcpy.p0i8.p0i8.i64
Intrinsic has incorrect argument type!
void (i8*, i8*, i64, i32, i1)* @llvm.memcpy.p0i8.p0i8.i64
Intrinsic has incorrect argument type!
void (i8*, i8*, i64, i32, i1)* @llvm.memcpy.p0i8.p0i8.i64
Intrinsic has incorrect argument type!
void (i8*, i8*, i64, i32, i1)* @llvm.memcpy.p0i8.p0i8.i64
 in /home/ammarfaizi2/project/now/php-compiler/vendor/ircmaxell/php-llvm/lib/LLVMAbstract/Module.php:180
Stack trace:
#0 /home/ammarfaizi2/project/now/php-compiler/lib/JIT/Context.php(210): PHPLLVM\LLVMAbstract\Module->verify(4, 'Intrinsic has i...')
#1 /home/ammarfaizi2/project/now/php-compiler/lib/JIT/Context.php(167): PHPCompiler\JIT\Context->compileCommon()
#2 /home/ammarfaizi2/project/ in /home/ammarfaizi2/project/now/php-compiler/vendor/ircmaxell/php-llvm/lib/LLVMAbstract/Module.php on line 180
ammarfaizi2@berlin:~/project/now/php-compiler$ 

```

## PHP Version
```
PHP 7.4.0-dev (cli) (built: Apr 23 2019 08:25:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies
```

## OS Details
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Linux Lite 4.0"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

## Kernel Details
```
ammarfaizi2@berlin:~/project/now/php-compiler$ uname -vrpios
Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 GNU/Linux
```

**Comment by driusan** [comment]
What LLVM version?

**Comment by ircmaxell** [comment]
So, that error signifies that you have an LLVM version mismatch. The syntax for the intrinsics `memcpy` and `memset` had their syntax change sometime between LLVM 4 and LLVM 7. In LLVM4 they had an additional `alignment` parameter, and it was removed by LLVM7.

I found the bug in PHP-LLVM where LLVM8 was using the old version instead of the new one.

So I assume you're using LLVM8? If so, try doing a composer update to fetch the bug fix in PHP-LLVM and try again.

**Comment by ammarfaizi2** [comment]
Yes, I use LLVM8.

I did composer update and it still the same. I even tried to delete the vendor dir including composer.lock and did the composer install again.

## Latest commit for php-llvm in vendor dir
```
ammarfaizi2@berlin:~/project/now/php-compiler/vendor/ircmaxell/php-llvm$ git log -n 1
commit 000910a47e3e15d134502b689e02ba03f5f2ecd1 (HEAD -> master, origin/master, origin/HEAD, composer/master)
Author: Anthony Ferrara <ircmaxell@gmail.com>
Date:   Tue Apr 23 09:14:13 2019 -0400

    Fix issue with LLVM8 using the wrong factory
ammarfaizi2@berlin:~/project/now/php-compiler/vendor/ircmaxell/php-llvm$ 
```

## LLVM Version
```
ammarfaizi2@berlin:~/project/now/php-compiler$ llvm-config --version
8.0.1
ammarfaizi2@berlin:~/project/now/php-compiler$ 
```

## Still get the same error
![The same error](https://user-images.githubusercontent.com/26004054/56636672-bb4b2300-6693-11e9-8072-700f918cd79c.png)

## Confirming LLVM version to be used
I also tried to confirm the LLVM version choosed by PHPLLVM chooser.
![Check](https://user-images.githubusercontent.com/26004054/56636441-fb5dd600-6692-11e9-9350-e3527743b60b.png)

![LLVM8 Confirmed](https://user-images.githubusercontent.com/26004054/56636529-44ae2580-6693-11e9-9fb0-98b9d29b48fe.png)

**Comment by ircmaxell** [comment]
I was able to reproduce and have fixed locally with https://github.com/ircmaxell/php-llvm/commit/fb89dc0253d0f2c2875007706a551d00490a0920

Can you confirm this works for you?

**Comment by ammarfaizi2** [comment]
Nice, thanks.

The JIT is now fixed.

But the AOT needs to use clang-4.0. Do we have some reasons of why we must use clang-4.0?

![abc](https://user-images.githubusercontent.com/26004054/56777585-99b97b00-67fc-11e9-87f0-f17357915828.png)

**Comment by ircmaxell** [comment]
Can you test https://github.com/ircmaxell/php-compiler/pull/66 ?

**Comment by ammarfaizi2** [comment]
Nice, thanks.
It works.

![asdf](https://user-images.githubusercontent.com/26004054/56779301-95915b80-6804-11e9-936c-d904bf01822e.png)

**Comment by ircmaxell** [comment]
Sweet, thanks!!!
