### ISSUE TITLE
Argument 1 passed to PHPCompiler\Compiler::compileOps() must be of the type array, object given

### ISSUE THREAD

**Issue by Sarke** [ircmaxell/php-compiler#74]
> Fatal error: Uncaught TypeError: Argument 1 passed to PHPCompiler\Compiler::compileOps() must be of the type array, object given, called in /compiler/lib/Compiler.php on line 113 and defined in /compiler/lib/Compiler.php:60
Stack trace:
#0 /compiler/lib/Compiler.php(113): PHPCompiler\Compiler->compileOps(Object(PHPCfg\Block), Object(PHPCompiler\Block))
#1 /compiler/lib/Compiler.php(100): PHPCompiler\Compiler->compileClassBody(Object(PHPCfg\Block), 19)
#2 /compiler/lib/Compiler.php(70): PHPCompiler\Compiler->compileClassLike(Object(PHPCfg\Op\Stmt\Class_), Object(PHPCompiler\Block))
#3 /compiler/lib/Compiler.php(57): PHPCompiler\Compiler->compileOps(Array, Object(PHPCompiler\Block))
#4 /compiler/lib/Compiler.php(51): PHPCompiler\Compiler->compileBlock(Object(PHPCompiler\Block))
#5 /compiler/lib/Compiler.php(29): PHPCompiler\Compiler->compileCfgBlock(Object(PHPCfg\Block))
#6 /compiler/lib/Runtime.php(136): PHPCompiler\Compiler->compile(Object(PHPCfg\Script))
#7 /compiler/lib/Runtime.php(159): PHPCompiler\Runtime->compile(Obj in /compiler/lib/Compiler.php on line 60

To reproduce:

```sh
docker run ircmaxell/php-compiler:16.04 -r 'class A { public int $i = 0; }'
```

**Comment by ircmaxell** [comment]
Classes aren't supported yet, so :)
