### ISSUE TITLE
Uncaught FFI\Exception: Cannot instantiate FFI\CData of zero size 

### ISSUE THREAD

**Issue by NeroAdvents** [ircmaxell/php-compiler#76]
Hi,

Hi encountered some issues using the php compiler on a simple test file printing "Hello World":
```
➜  php-compiler git:(master) ✗ php bin/compile.php test.php
PHP Fatal error:  Uncaught FFI\Exception: Cannot instantiate FFI\CData of zero size in /home/nordine/PhpstormProjects/php-compiler/php-compiler/vendor/ircmaxell/php-llvm/ffi/llvm4.php:1602
Stack trace:
#0 /home/nordine/PhpstormProjects/php-compiler/php-compiler/vendor/ircmaxell/php-llvm/ffi/llvm4.php(1602): FFI->new()
#1 /home/nordine/PhpstormProjects/php-compiler/php-compiler/vendor/ircmaxell/php-llvm/lib/LLVMAbstract/Context.php(100): llvm\llvm->makeArray()
#2 /home/nordine/PhpstormProjects/php-compiler/php-compiler/lib/JIT/Context.php(149): PHPLLVM\LLVMAbstract\Context->functionType()
#3 /home/nordine/PhpstormProjects/php-compiler/php-compiler/lib/JIT/Context.php(101): PHPCompiler\JIT\Context->defineBuiltins()
#4 /home/nordine/PhpstormProjects/php-compiler/php-compiler/lib/Runtime.php(105): PHPCompiler\JIT\Context->__construct()
#5 /home/nordine/PhpstormProjects/php-compiler/php-compiler/lib/Runtime.php(153): PHPCompiler\Runtime->loadJitContext()
#6 /home/nordine/PhpstormProjects/php-compiler/php-compiler/bin/compile.php(30 in /home/nordine/PhpstormProjects/php-compiler/php-compiler/vendor/ircmaxell/php-llvm/ffi/llvm4.php on line 1602
```

And I wanted to know if your compiler was compatible with CakePHP ? I want to upgrade the performance and obfuscate my code by compiling the source code as shared objects (.so). 

If anyone can help, would be appreciated.
Thanks.

**Comment by SalimF** [comment]
I got exact same issue , looks like nobody replies here .
